blank_issues_enabled: false
contact_links:
    - name: Ask a Question 💡
      url: https://github.com/composer-unused/symbol-parser/discussions/new?category=q-a
      about: Ask the community for help
    - name: Feature Request ❓
      url: https://github.com/composer-unused/symbol-parser/discussions/new?category=ideas
      about: Share ideas for new features
